### ISSUE TITLE
how to setup attack vector

### ISSUE THREAD

**Issue by CRAJKUMARSINGH** [UndeadSec/SocialFish#157] opened 2019-06-30 09:04 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tacticalDevC** [comment] 2019-12-17 19:26
Go to http://0.0.0.0:5000/neptune type in the URL you want to clone and type in an URL you want the victim to be redirected to after "logging in". Click on the lightning and you're finished.

Can now somebody close this issue?

Note: Try to fill out the issue template next time. Maybe then you wouldn't be ignored.

**Comment by hwac121** [comment] 2020-06-15 15:17
No, DO NOT close this issue. The problem is people are getting this when they go to the URL:
You have not yet set up an attack vector

So, the question is how the hell to setup an attack vector since there is nothing in the instructions on how to do so...

**Comment by tacticalDevC** [comment] 2020-06-15 15:32
Okay so you set up SF to clone an url and when visiting the phishing link it shows you that no attack vector has been set up? I can't solve the problem with just an issues title. Please give me a clear description of the steps you went through to get to this error.

**Comment by hwac121** [comment] 2020-06-16 02:26
> Okay so you set up SF to clone an url and when visiting the phishing link it shows you that no attack vector has been set up? I can't solve the problem with just an issues title. Please give me a clear description of the steps you went through to get to this error.

No, no...please don't take me wrong. You explained what the issue is and how to fix it perfectly. You just missed one thing you didn't explain that I am pretty sure is what is throwing folks. The fact that the instructions pretty much tell you to go to http://0.0.0.0:5000 but unless you have used it before you do not know to go to http://0.0.0.0/neptune. 
I worked support for years, I am telling you, even though you explained it perfectly, and I understood it just fine, people frustrated and looking for an answer will only see the same thing they thought they already tried, go to http://0.0.0.0:5000 again and be more pissed not understanding unless you spell it out and MAKE them see the difference. Then the little light bulb goes off and they say, "OOoooooh, now I get it!" LOL

And btw, I looked at my post and it looks really smartass, I'd slap me if I read that. LMAO!!! Forgive how that came across. What can I say I am an IT Director and software engineer so my bedside manner sucks, sorry bout that. LOL

**Closed** 2021-11-11 18:56 UTC

**Comment by GitHubGalaxyGitHubGalaxy** [comment] 2024-04-10 20:40
You have not yet set up an attack vector  
why that typ text show instead of dashboard

**Comment by GitHubGalaxyGitHubGalaxy** [comment] 2024-04-10 20:46
when i open this url http://127.0.0.1:5000
in browser .This show a picture of fish instead of dashboard on which this text has been written (ou have not yet set up an attack vector)

**Comment by GitHubGalaxyGitHubGalaxy** [comment] 2024-04-10 20:48
> when i open this url http://127.0.0.1:5000 in browser .This show a picture of fish instead of dashboard on which this text has been written (you have not yet set up an attack vector)
