### ISSUE TITLE
ModuleNotFoundError: No module named 'pylatex'

### ISSUE THREAD

**Issue by proton111** [UndeadSec/SocialFish#147] opened 2019-04-30 09:12 UTC
I am trying to run SocialFish using python and God knows the struggle I am having to install this simple software for the past 3 days- some 6 hrs of trouble shooting each day.

I had "No module named nmap" error before and I just resolved it and ran SocialFish.py again. Now I have "No Module named pylatex" error and when I google this error and almost no result had any forum dealing with this error.

When I run "pip3 install pylatex" or "pip install pylatex" it says "Requirement already satisfied". It means pylatex is installed in my system but it still shows "No module named pylatex".

Someone pls help. Why am I experiencing so many "No module" errors with python3.
Thanks in advance.

Here is my commands:

**_```
$sudo python3 SocialFish.py
Traceback (most recent call last):
File "SocialFish.py", line 13, in 
from core.report import generate_unique #>> new line
File "/home/proton/Desktop/SocialFish/core/report.py", line 2, in 
from pylatex import Document, PageStyle, Head, Foot, MiniPage, 
ModuleNotFoundError: No module named 'pylatex'
```_**

**Comment by A1S0N** [comment] 2019-05-13 10:53
Must be a problem of your internal system.
Try it on another OS, and tell us if the problem is fixed now.

**Closed** 2021-11-11 18:56 UTC
Labels: invalid
