### ISSUE TITLE
File "SocialFish.py", line 2, in <module>     from flask import Flask, request, render_template, jsonify, redirect, g, flash ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by IamFadedGamer** [UndeadSec/SocialFish#145] opened 2019-04-17 17:36 UTC
![Screenshot from 2019-04-17 17-32-54](https://user-images.githubusercontent.com/49586957/56308609-40d04f80-6137-11e9-9d3b-3e70b1121039.png)

**Comment by nutcracker181** [comment] 2019-04-19 00:42
try pip install flask

**Comment by proton111** [comment] 2019-04-19 00:53
> try pip install flask


(I also have the same issue)
That does not work. When I do that, I get this. 

**_**DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: flask in /usr/local/lib/python2.7/dist-packages (1.0.2)
Requirement already satisfied: Werkzeug>=0.14 in /usr/local/lib/python2.7/dist-packages (from flask) (0.15.2)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python2.7/dist-packages (from flask) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python2.7/dist-packages (from flask) (1.1.0)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python2.7/dist-packages (from flask) (2.10.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.10->flask) (1.1.1)_**_**

I have also tried <pip3 install flask> and I get this:
**Requirement already satisfied: flask in /usr/lib/python3/dist-packages (1.0.2)
root@kali:~#**

What could be the reason?

Here is the error again:
**ModuleNotFoundError: No module named 'flask'**

Any help would be much appreciated. Thanks in advance.

**Comment by ItsHerkules** [comment] 2019-04-29 08:29
Before executing you have to type "sudo pip install -r requirements.txt

**Comment by A1S0N** [comment] 2019-05-13 11:00
It's a problem with your internal OS, can you tell us if the problem is fixed now?

**Comment by MrFoxyBR** [comment] 2019-07-14 20:37
sudo python -m pip uninstall request
Once uninstalled re-install it.
sudo python -m pip install request

**Comment by pruthvirajchavan** [comment] 2019-11-04 21:02
ModuleNotFoundError: No module named 'nmap'

**Comment by Likhithlpu** [comment] 2020-08-05 06:08
Same issue 

Traceback (most recent call last):
  File "SocialFish.py", line 5, in <module>
    from core.view import head
  File "/home/kali/SocialFish/core/view.py", line 11
SyntaxError: Non-ASCII character '\xe2' in file /home/kali/SocialFish/core/view.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Closed** 2021-11-11 18:56 UTC
